<?php
// app/Notifications/NewMessage.php
namespace App\Notifications;
 
use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use App\User;
use App\Documents;
use Illuminate\Support\Facades\URL;
use view;

class NewMessage extends Notification
{
    use Queueable;
    public $fromUser;
    public $document;
 
    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct(User $user, Documents $document)
    {
        $this->fromUser = $user;
        $this->document = $document;
    }
 
    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return ['mail'];
    }
 
    /**
     * Get the mail representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail($notifiable)
    {
        $subject = sprintf('%s: You\'ve got a new message from %s!', config('app.name'), $this->fromUser->name);
        $greeting = sprintf('Dear Mr/Mrs %s!', $notifiable->name);
        
        
        if ($this->document->doc_status == 'Completed') {
            # code...
            $url = URL::signedRoute('documents.show', ['document' => $this->document->id]);
            $information = 'was <b>APPROVED</b>';
        } else {
            # code...
            $url = URL::signedRoute('documents.needAction', ['document' => $this->document->id]);
            $information = 'need your action';
        }
        
        return (new MailMessage)
                    ->subject($subject)
                    ->greeting($greeting)
                    ->salutation('<b>Best regards</b>,')
                    ->line('Document with the following number <b>'.$this->document->doc_number.'</b>')//
                    ->line(''. $information.' Please click link below to see details')
                    ->action('Notification Action', $url)
                    ->line('This email generated by system, please dont reply!');
    }
 
    /**
     * Get the array representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function toArray($notifiable)
    {
        return [
            //
        ];
    }
}